import Head from "next/head";
// import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "./components/layout/header";
import  MainBody  from "./components/layout/main_body";
import  Footer  from "./components/layout/footer";

// const inter = Inter({ subsets: ["latin"] });

export default function Home( {title} ) {
  return (
    <>
      <Head>
        <title> { title? title + "-Costco": "Welcome to Costco Wholesale"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div  className= {styles.main}>
        <Header />
        <MainBody />
        <Footer />
      </div>
    </>
  );
}
